name: old_buildings
description: "App that match region buildings"
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  auto_route: ^7.8.4
  geolocator: ^10.1.0
  maps_toolkit: ^3.0.0
  flutter_map: ^5.0.0
  flutter_map_location_marker: ^7.0.5
  flutter_map_supercluster: ^4.3.0
  slang: ^3.27.0
  slang_flutter: ^3.27.0
  flex_color_scheme: ^7.3.1
  flutter_tts: ^3.8.5

dev_dependencies:
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

